version: '2'
services:
    customerservice-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/customerService/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
            - MYSQL_DATABASE=customerservice
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
